version: "3.0"
nlu:
- intent: faq/ask_report
  examples: |
    - Quero fazer uma denuncia de maus tratos
    - Gostaria de fazer uma denuncia de maus tratos
    - Quero fazer uma denuncia
    - Gostaria de fazer uma denuncia
- intent: faq/ask_collect_warn
  examples: |
    - Tem consequências se eu enterrar meu bicho por conta própria?
    - E se eu enterrar meu proprio pet no quintal
    - posso enterrar meu [gato](animal_type_entity) no quintal?
    - posso enterrar meu proprio cachorro quando ele morrer?
    - posso enterrar meu cachorro no meu quintal?
- intent: faq/ask_lost_pet
  examples: |
    - Meu cachorro sumiu, ele é vira-lata caramelo, manda uma msg para mim
    - Vocês podem me ajudar a achar meu [gato](animal_type_entity)?
    - Perdi meu cachorro
    - Perdi meu pet
    - Perdi meu cachorro, o que eu faço?
    - Meu [gato](animal_type_entity) sumiu
    - Perdi meu [gato](animal_type_entity)
- intent: faq/ask_veterinarian
  examples: |
    - Onde posso conseguir o contato do veterinario ?
    - Pode me passar o numero do veterinario ?
    - Pode me passar o contato do veterinario ?
    - atendimento veterinário
    - Quero o contato do veterinario
    - Pode me mandar o contato do veterinario ?
- intent: faq/ask_how_to_donate_animal
  examples: |
    - detalhes da doação
    - quero doar
    - doar
    - doacao
    - como faço para doar?
    - fazer doação
    - resgatei e quero doar
- intent: faq/ask_collect
  examples: |
    - o que fazer quando meu [gato](animal_type_entity) morrer?
    - com quem eu falor quando o bicho morre?
    - o que fazer quando meu cachorro morrer?
    - meu pet morreu e agora?
    - pra quem eu ligo quando meu [gato](animal_type_entity) morre?
    - como proceder quando meu pet morre?
    - com quem eu falor quando meu cachorro morre?
- intent: faq/ask_vaccine_dog
  examples: |
    - quando vacinar meus [cães](animal_type_entity)
    - calendario de vacinação para [cachorros](animal_type_entity)
    - quero saber de vacinas para [cachorro](animal_type_entity)
    - me fale sobre vacinas para [cachorro](animal_type_entity)
    - vacinação de [cachorro](animal_type_entity)
    - vacinação para [cães](animal_type_entity)
    - vacina para [cão](animal_type_entity)
    - quando vacinar meu cão
- intent: faq/ask_found_and_rescued
  examples: |
    - Peguei um cachorrinho na rua, o que eu faço?
    - Resgatei um animal de rua e agora?
    - Encontrei um cachorro na rua, o que devo fazer ?
    - Encontrei um [gato](animal_type_entity) perdido na rua, o que devo fazer?
    - Eu encontrei um animal na rua, o que eu faço?
    - Resgatei um animal, o que devo fazer?
    - O que eu faço? Encontrei um animal perdido na rua
    - Encontrei um animal perdido, o que eu faço?
- intent: faq/ask_need_rescue
  examples: |
    - ferido
    - preciso de resgate
    - tem um cachorro ferido
    - machucado
    - o [gato](animal_type_entity) está dolorido
    - Preciso que alguém resgate um [gato](animal_type_entity) abandonado
    - gatinho atropelado
    - encontrei um pet ferido
    - machucou a perna
- intent: faq/ask_vaccine_cat
  examples: |
    - calendario de vacinação para gatos
    - vacina para [gato](animal_type_entity)
    - vacinação para gatos
    - me fale sobre vacinas para [gato](animal_type_entity)
    - como faço para vacinar meus gatos
    - quando vacinar meu [gato](animal_type_entity)
    - vacinação de [gato](animal_type_entity)
    - vacinação para [gato](animal_type_entity)
    - quero saber de vacinas para [gato](animal_type_entity)
- intent: askaction/ask_disease
  examples: |
    - como é feito o [tratamento](question) da [raiva](disease)?
    - como posso o [tratamento](question) do meu animal para que ele não tenha [cinomose](disease)?
    - como [previnir](question) a [raiva](disease)?
    - qual a [prevenção](question) pra [raiva](disease)?
    - você sabe qual a [prevenção](question) para [carrapato](disease)?
    - [tratamento](question) para [sarna](disease)?
    - qual a [prevenção](question) para [leishmaniose](disease) ?
    - o que devo fazer como [prevenção](question) meu animal com [sarna](disease)?
    - como [prevenir](question) a [cinomose](disease)?
    - como [tratar](question) a [parvovirose](disease)?
    - [tratamento](question) para [fiv] felina(disease)?
    - qual a [prevenção](question) pra [carrapato](disease)?
    - como [tratar](question) a [fiv] felina (disease)?
    - qual o [sintoma] presente no vírus da [raiva](question) ?
    - como se [prevenir](question) para [fiv] felina(disease)?
    - quais são os [sintomas](question) que meu animal pode sentir se estiver com [cinomose](disease)?
    - fale sobre [sarna](disease)
    - informações sobre [fiv] felina(disease)?
    - como se [prevenir](question) da doença do [carrapato](disease)?
    - qual os [sintomas](question) da doença do [carrapato](disease)?
    - [tratamento](question) para [parvovirose](disease)?
    - o que devo fazer para [tratar](question) da [cinomose](disease)?
    - me fale sobre [leishmaniose](disease)
    - quais os [tratamentos](question) para [carrapato](disease)?
    - qual o [sintoma](question) da [parvovirose](disease)?
    - qual a [prevenção](question) pra [parvovirose](disease)?
    - qual o [sintoma](question) da [fiv] felina(disease)?
    - qual o [tratamento](question) disponivel para [leishmaniose](disease) ?
    - o que você sabe sobre [cinomose](disease)?
    - [sintomas](question) para [fiv] felina(disease)?
    - como [prevenir](question) a [fiv] felina(disease)?
    - qual a [prevenção](question) pra [fiv]felina(disease)?
    - qual os [sintomas](question) da [raiva](disease)?
    - como se [prevenir](question) da [leishmaniose](disease)?
    - me dê informações sobre [raiva](disease)
    - qual o procedimento para [tratar](question) a [raiva](question)?
    - o que é [leishmaniose](disease)
    - como [tratar](question) o animal com [leishmaniose](disease)?
- intent: human_service_intent
  examples: |
    - Quero falar com uma pessoa
    - Atendimento humano
    - Quero um humano
    - Me passa para uma pessoa
    - Eu quero atendimento humano
- intent: out_of_scope_intent
  examples: |
    - Adotar um papagaio
    - Quero uma pizza
    - Montar numa capivara
    - Assistir series
    - Teste 123 teste 321
- intent: thank_you_intent
  examples: |
    - thanks
    - valeu
    - gracias
    - é isso aí
    - vlw
    - obrigado
- intent: bot_purpose_intent
  examples: |
    - O que você faz?
    - o que você pode fazer?
    - propósito
    - o que posso perguntar?
    - Pra que você serve?
- intent: donation_intent
  examples: |
    - dar dinheiro para ONG
    - ajudar com areia
    - ajudar com dinheiro
    - doar medicamento
    - doar ração para cachorro
    - doacao de areia
- intent: volunteer_intent
  examples: |
    - Como posso me voluntariar?
    - Voluntário
    - Quero ser voluntário
    - Quero auxiliar com meu tempo
    - Quero fazer parte do voluntariado
    - Gostaria de voluntariar
- intent: deny_intent
  examples: |
    - cancelo
    - nenhum
    - negativo
    - nunca
    - jamais
    - nego
    - n
    - errado
- intent: adopt_intent
  examples: |
    - quero um [cachorro](animal_type_entity)
    - como faço para adotar um animal?
    - como eu adoto?
    - desejo adotar um [gatinho](animal_type_entity)
    - quero um [gato](animal_type_entity)
    - adotar
    - posso adotar um pet ?
    - Como adotar um [cão](animal_type_entity)
- intent: affirm_intent
  examples: |
    - afirmo
    - sim
    - ok
    - exato
    - confirmo
    - afirmativo
    - correto
    - s
    - isso mesmo
- intent: wanna_help_intent
  examples: |
    - Como ajudo o abrigo?
    - Gostaria de ajudar
    - Como posso auxiliar?
    - Eu quero ajudar
    - Quero ajudar
    - O que posso fazer para ajudar a ong?
    - Desejo ajudar de alguma maneira
    - O que eu posso fazer para ajudar?
    - O que eu consigo fazer para ajuda-los?
    - Como posso ajudar vocês?
- intent: goodbye_intent
  examples: |
    - xau
    - bye
    - se cuida
    - até mais
    - tchau
    - ate
    - TCHAU
    - Tchau
    - flw
    - te vejo dps
    - até uma proxima
- intent: ask_castration_intent
  examples: |
    - quero castrar cachorro
    - Conte-me como ocorre o processo de castração
    - castramento de gato
    - Quero saber como funciona a castração
    - Processo de castração
    - como funciona castração
    - castração de cachorro
    - Como funciona o processo de castração?
    - Castração
    - Como ocorre o processo de castração ?
    - quero castrar gato
- intent: greet_intent
  examples: |
    - oi oi
    - hi
    - boa tarde
    - olá
    - Oi
    - oi
    - Oie
    - oiiii
    - OI
    - bom dia
    - salve
    - boa noite
    - tudo bom?
    - Oi Oi
- regex: question
  examples: |
    - /([A-Z a-z])/
- lookup: disease
  examples: |
    - leishmaniose
    - raiva
    - sarna
    - parvovirose
    - cinomose
    - fiv
    - carrapato
- lookup: question
  examples: |
    - sintomas
    - prevenção
    - tratamento
    - prevenir
    - tratar
    - sintoma
