version: "3.0"
nlu:
- intent: faq/ask_report
  examples: |
    - Quero fazer uma denuncia
    - Gostaria de fazer uma denuncia
    - Gostaria de fazer uma denuncia de maus tratos
    - Como faço uma denuncia de maus tratos ?
- intent: faq/ask_collect_warn
  examples: |
    - posso enterrar meu próprio gato quando ele morrer?
    - posso enterrar meu cachorro no meu quintal?
    - posso enterrar meu gato no quintal?
    - E se eu enterrar meu proprio pet no quintal
    - Tem consequências se eu enterrar meu bicho por conta própria?
- intent: faq/ask_lost_pet
  examples: |
    - Meu cachorro sumiu, ele é vira-lata caramelo, manda uma msg para mim
    - Meu pet desapareceu
    - Perdi meu gato
    - Perdi meu cachorro
    - Perdi meu pet
    - Perdi meu cachorro, o que eu faço?
    - Vocês podem me ajudar a achar meu gato?
- intent: faq/ask_veterinarian
  examples: |
    - Pode me mandar o contato do veterinario ?
    - atendimento veterinário
    - Pode me passar o numero do veterinario ?
    - Quero o contato do veterinario
    - Pode me passar o contato do veterinario ?
    - Quero entrar em contato com o veterinario
- intent: faq/ask_how_to_donate_animal
  examples: |
    - desejo doar um pet
    - quero doar
    - doacao
    - fazer doação
    - como faço para doar?
    - doar
    - resgatei e quero doar
- intent: faq/ask_collect
  examples: |
    - com quem eu falor quando o bicho morre?
    - o que eu faço quando meu bichinho morre?
    - meu pet morreu e agora?
    - como proceder quando meu pet morre?
    - pra quem eu ligo quando meu gato morre?
    - com quem eu falor quando meu cachorro morre?
    - qual número eu ligo quando meu animal morre?
- intent: faq/ask_found_and_rescued
  examples: |
    - Resgatei um animal, o que devo fazer?
    - Peguei um cachorrinho na rua, o que eu faço?
    - Resgatei um cachorro de rua e agora?
    - Encontrei um animal perdido, o que eu faço?
    - Encontrei perdido e resgatei e agora?
    - Resgatei um animal de rua e agora?
    - Encontrei um gato perdido na rua, o que devo fazer?
    - Encontrei um cachorro na rua, o que devo fazer ?
    - Eu encontrei um animal na rua, o que eu faço?
- intent: faq/ask_need_rescue
  examples: |
    - ferido
    - machucado
    - resgatei um animal machucado
    - Preciso que alguém resgate um gato abandonado
    - encontrei um pet ferido
    - tem um cachorro ferido
    - gatinho atropelado
    - preciso de resgate
    - o gato está dolorido
- intent: askaction/ask_disease
  examples: |
    - qual a [prevenção](question) para [leishmaniose](disease) ?
    - como se [prevenir](question) para [sarna](disease)?
    - como [previnir](question) a [raiva](disease)?
    - como [prevenir](question) a [cinomose](disease)?
    - como [prevenir](question) a [fiv](disease)?
    - como se [prevenir](question) da [leishmaniose](disease)?
    - como [tratar](question) a [parvovirose](disease)?
    - qual o procedimento para [tratar](question) a [raiva](question)?
    - como [prevenir](question) a [parvovirose](disease)?
    - fale sobre [sarna](disease)
    - qual os [sintomas](question) da [raiva](disease)?
    - como se [prevenir](question) para [fiv](disease)?
    - como é feito o [tratamento](question) da [raiva](disease)?
    - qual o [sintoma] presente no vírus da [raiva](question) ?
    - quais os [tratamentos](question) para [carrapato](disease)?
    - como [tratar](question) a [fiv](disease)?
    - o que devo fazer como [prevenção](question) meu animal com [sarna](disease)?
    - qual a [prevenção](question) pra [fiv](disease)?
    - o que é [leishmaniose](disease)
    - como [tratar](question) a [sarna](disease)?
    - [tratamento](question) para [fiv](disease)?
    - qual o [sintoma](question) da [parvovirose](disease)?
    - qual o [sintoma](question) presente na [sarna](disease)?
    - [tratamento](question) para [parvovirose](disease)?
    - como se [prevenir](question) da doença do [carrapato](disease)?
    - você sabe qual a [prevenção](question) para [carrapato](disease)?
    - qual o [sintoma](question) da [fiv](disease)?
    - como posso o [tratamento](question) do meu animal para que ele não tenha [cinomose](disease)?
    - qual a [prevenção](question) pra [raiva](disease)?
    - me dê informações sobre [raiva](disease)
    - como [tratar](question) o animal com [leishmaniose](disease)?
    - [tratamento](question) para [sarna](disease)?
    - o que devo fazer para [tratar](question) da [cinomose](disease)?
    - qual o [tratamento](question) disponivel para [leishmaniose](disease) ?
    - você sabe qual a [prevenção](question) para [cinomose](disease)?
- intent: human_service_intent
  examples: |
    - Quero falar com uma pessoa
    - Eu quero atendimento humano
    - Me passa para uma pessoa
    - Quero falar com um atendente
    - Quero um humano
- intent: out_of_scope_intent
  examples: |
    - Assistir series
    - Montar numa capivara
    - batatinha 1 2 3
    - Quero uma pizza
    - Adotar um papagaio
- intent: thank_you_intent
  examples: |
    - obrigado
    - valeu
    - gracias
    - vlw
    - é isso aí
- intent: adopt_intent
  examples: |
    - quero adotar
    - adotar
    - como faço para adotar um animal?
    - como eu adoto?
    - adoção
    - posso adotar um pet ?
- intent: bot_purpose_intent
  examples: |
    - Qual seu objetivo
    - Pra que você serve?
    - propósito
    - Quais suas opções?
    - o que você pode fazer?
    - O que você faz?
- intent: ask_castration_intent
  examples: |
    - Como ocorre o processo de castração ?
    - Quero saber como funciona a castração
    - Pode me dizer como funciona o processo de castração ?
    - Como funciona o processo de castração?
    - Castração
- intent: donation_intent
  examples: |
    - doacao de areia
    - ajudar com dinheiro
    - dar dinheiro para ONG
    - doar medicamento
    - doar ração para cachorro
    - ajudar com areia
- intent: volunteer_intent
  examples: |
    - Gostaria de voluntariar
    - Quero fazer parte do voluntariado
    - Voluntário
    - voluntario
    - Quero auxiliar com meu tempo
    - Como faço para voluntariar
- intent: goodbye_intent
  examples: |
    - bjs
    - ate
    - se cuida
    - bye
    - flw
    - xau
    - tchau
    - te vejo dps
- intent: deny_intent
  examples: |
    - nego
    - errado
    - cancelo
    - nenhum
    - jamais
    - nao
    - nunca
    - n
- intent: affirm_intent
  examples: |
    - afirmo
    - confirmo
    - certo
    - exato
    - claro
    - s
    - ok
    - afirmativo
    - correto
- intent: greet_intent
  examples: |
    - oi
    - tarde
    - hi
    - boa noite
    - dia
    - oiiii
    - olá
    - boa tarde
    - noite
    - eae
- intent: wanna_help_intent
  examples: |
    - Quero ajudar
    - O que eu posso fazer para ajudar?
    - Como posso auxiliar?
    - Como ajudo o abrigo?
    - Como eu ajudo vocês?
    - O que posso fazer para ajudar a ong?
    - Eu quero ajudar
    - Como posso ajudar vocês?
    - Gostaria de ajudar
- regex: question
  examples: |
    - /([A-Z a-z])/
- lookup: disease
  examples: |
    - leishmaniose
    - raiva
    - sarna
    - parvovirose
    - cinomose
    - fiv
    - carrapato
- lookup: question
  examples: |
    - sintomas
    - prevenção
    - tratamento
    - prevenir
    - tratar
    - sintoma
